"""Curated, source-verified catalogue of real Lebanese places.

This module is DATA, not sample content. Every record describes a real place in
Lebanon with real coordinates, drawn from public reference sources. Each record
carries a ``source_url`` pointing at the exact reference page used, so any value
here is human-checkable. Nothing is invented:

* Coordinates are real and validated to fall inside Lebanon (see LEBANON_BBOX).
* Names/labels use each place's established English, Arabic and French forms.
  Where an established localisation is not known, that locale is left ``None``
  rather than machine-translated (proper names are never faked).
* No ratings, prices, phone numbers or opening hours are asserted. Those fields
  stay empty/NULL unless a provider later supplies verified values.
* ``image_commons`` names a Wikimedia Commons file. The importer resolves it to a
  real URL, confirms the licence is reusable, records the attribution, and only
  then publishes it. If the licence cannot be confirmed the listing stays
  imageless — a wrong or unlicensed image is never attached.

Identity / idempotency: ``slug`` is the stable key. The experience row is keyed
on ``slug``; the venue records ``source_reference = 'curated:<slug>'`` and
``location_source = 'curated'`` for provenance. Re-running the importer upserts
on these keys and never duplicates.

Taxonomy: ``category`` is one of the five catalogue facets already defined in the
schema (culture, nature, coast, adventure, city). Finer classification (castle,
waterfall, museum, winery, ...) is carried as normalised ``tags`` so no parallel
category model is introduced and the existing filters keep working.
"""

from __future__ import annotations

from typing import TypedDict

# Lebanon bounding box (a generous rectangle around the country's land borders).
# Any coordinate outside this box is rejected by the importer before insert.
LEBANON_BBOX = {
    "lat_min": 33.02,
    "lat_max": 34.70,
    "lng_min": 35.08,
    "lng_max": 36.66,
}

# Governorate destinations (the 8 muhafazat). These become app.destinations rows
# so every experience hangs off a real, published place in the tree. Featured
# strip curation (public_catalogue_destinations) is unchanged; these power
# filtering, search and the "place · region" label.
GOVERNORATES: list[dict[str, str]] = [
    {
        "slug": "beirut",
        "name_en": "Beirut",
        "name_ar": "بيروت",
        "name_fr": "Beyrouth",
        "region": "Beirut",
        "lat": 33.8938,
        "lng": 35.5018,
        "blurb_en": "The capital: seafront corniche, museums, and old and new streets.",
    },
    {
        "slug": "mount-lebanon",
        "name_en": "Mount Lebanon",
        "name_ar": "جبل لبنان",
        "name_fr": "Mont-Liban",
        "region": "Mount Lebanon",
        "lat": 33.8100,
        "lng": 35.6500,
        "blurb_en": "Coast to summit: grottoes, shrines, ski slopes and mountain villages.",
    },
    {
        "slug": "north-lebanon",
        "name_en": "North Lebanon",
        "name_ar": "لبنان الشمالي",
        "name_fr": "Liban-Nord",
        "region": "North Lebanon",
        "lat": 34.4360,
        "lng": 35.8497,
        "blurb_en": "Tripoli's old city, the cedars, and the Qadisha valley.",
    },
    {
        "slug": "akkar",
        "name_en": "Akkar",
        "name_ar": "عكار",
        "name_fr": "Akkar",
        "region": "Akkar",
        "lat": 34.5400,
        "lng": 36.1000,
        "blurb_en": "Lebanon's green north-east corner: high forests, plains and old citadels.",
    },
    {
        "slug": "beqaa",
        "name_en": "Beqaa",
        "name_ar": "البقاع",
        "name_fr": "Beqaa",
        "region": "Beqaa",
        "lat": 33.8000,
        "lng": 35.9000,
        "blurb_en": "The valley of vineyards, the Umayyad city of Anjar, and Zahlé.",
    },
    {
        "slug": "baalbek-hermel",
        "name_en": "Baalbek-Hermel",
        "name_ar": "بعلبك الهرمل",
        "name_fr": "Baalbek-Hermel",
        "region": "Baalbek-Hermel",
        "lat": 34.0060,
        "lng": 36.2040,
        "blurb_en": "The great Roman temples of Baalbek and the upper Orontes.",
    },
    {
        "slug": "south-lebanon",
        "name_en": "South Lebanon",
        "name_ar": "لبنان الجنوبي",
        "name_fr": "Liban-Sud",
        "region": "South Lebanon",
        "lat": 33.5630,
        "lng": 35.3720,
        "blurb_en": "Sidon and Tyre on the coast, with sea castles and Roman cities.",
    },
    {
        "slug": "nabatieh",
        "name_en": "Nabatieh",
        "name_ar": "النبطية",
        "name_fr": "Nabatieh",
        "region": "Nabatieh",
        "lat": 33.3789,
        "lng": 35.4839,
        "blurb_en": "Inland hills, the Litani, and the Crusader stronghold of Beaufort.",
    },
]


# Normalised tag vocabulary (kind='tag'). Deduplicated, kebab-case, singular
# where it reads naturally. These label the finer type of each place.
TAG_LABELS: dict[str, str] = {
    "unesco": "UNESCO World Heritage",
    "archaeological-site": "Archaeological site",
    "roman": "Roman",
    "phoenician": "Phoenician",
    "crusader": "Crusader",
    "ottoman": "Ottoman",
    "mamluk": "Mamluk",
    "umayyad": "Umayyad",
    "castle": "Castle",
    "citadel": "Citadel",
    "palace": "Palace",
    "temple": "Temple",
    "museum": "Museum",
    "church": "Church",
    "mosque": "Mosque",
    "monastery": "Monastery",
    "shrine": "Shrine",
    "cave": "Cave",
    "waterfall": "Waterfall",
    "nature-reserve": "Nature reserve",
    "forest": "Forest",
    "cedars": "Cedars",
    "mountain": "Mountain",
    "ski": "Ski",
    "hiking": "Hiking",
    "viewpoint": "Viewpoint",
    "beach": "Beach",
    "seaside": "Seaside",
    "port": "Port",
    "marina": "Marina",
    "old-town": "Old town",
    "souk": "Souk",
    "village": "Village",
    "winery": "Winery",
    "river": "River",
    "lake": "Lake",
    "historic": "Historic",
    "landmark": "Landmark",
    "promenade": "Promenade",
    "garden": "Garden",
}


class Place(TypedDict, total=False):
    slug: str
    name_en: str
    name_ar: str | None
    name_fr: str | None
    governorate: str
    category: str  # culture | nature | coast | adventure | city
    listing_kind: str  # experience | attraction | restaurant
    tags: list[str]
    lat: float
    lng: float
    summary_en: str
    summary_ar: str | None
    summary_fr: str | None
    image_commons: str | None  # Wikimedia Commons "File:..." name (no "File:" prefix)
    source_url: str  # human-checkable reference for provenance


# ---------------------------------------------------------------------------
# The catalogue. Coordinates were cross-checked against each record's source_url
# while authoring, and are re-validated against LEBANON_BBOX at import time.
# ---------------------------------------------------------------------------
PLACES: list[Place] = [
    # ===================== BEIRUT =====================
    {
        "slug": "raouche-pigeon-rocks",
        "name_en": "Raouché (Pigeon Rocks)",
        "name_ar": "صخرة الروشة",
        "name_fr": "Rocher de Raouché",
        "governorate": "beirut",
        "category": "coast",
        "listing_kind": "attraction",
        "tags": ["landmark", "seaside", "viewpoint"],
        "lat": 33.8909,
        "lng": 35.4732,
        "summary_en": "Two offshore rock arches off Beirut's western cliffs, the city's best-known natural landmark and sunset spot.",
        "summary_ar": "صخرتان بحريتان قبالة الواجهة الغربية لبيروت، أشهر معالمها الطبيعية ومكان لمشاهدة الغروب.",
        "summary_fr": "Deux rochers en arche au large des falaises ouest de Beyrouth, le repère naturel le plus connu de la ville.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Raouch%C3%A9",
    },
    {
        "slug": "national-museum-beirut",
        "name_en": "National Museum of Beirut",
        "name_ar": "متحف بيروت الوطني",
        "name_fr": "Musée national de Beyrouth",
        "governorate": "beirut",
        "category": "culture",
        "listing_kind": "attraction",
        "tags": ["museum", "archaeological-site", "historic"],
        "lat": 33.8790,
        "lng": 35.5153,
        "summary_en": "Lebanon's principal archaeology museum, tracing the country from prehistory through the Phoenician, Roman and later periods.",
        "summary_ar": "المتحف الأثري الرئيسي في لبنان، يعرض تاريخ البلاد من عصور ما قبل التاريخ مروراً بالفينيقيين والرومان وما بعدهم.",
        "summary_fr": "Le principal musée archéologique du Liban, retraçant le pays de la préhistoire aux périodes phénicienne et romaine.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/National_Museum_of_Beirut",
    },
    {
        "slug": "mohammad-al-amin-mosque",
        "name_en": "Mohammad Al-Amin Mosque",
        "name_ar": "جامع محمد الأمين",
        "name_fr": "Mosquée Mohammad Al-Amin",
        "governorate": "beirut",
        "category": "culture",
        "listing_kind": "attraction",
        "tags": ["mosque", "landmark"],
        "lat": 33.8949694,
        "lng": 35.5063694,
        "summary_en": "The large blue-domed Ottoman-revival mosque on Martyrs' Square, completed in 2008 and a defining feature of the downtown skyline.",
        "summary_ar": "جامع كبير بقبته الزرقاء على ساحة الشهداء، اكتمل عام 2008 وبات معلماً بارزاً في وسط بيروت.",
        "summary_fr": "La grande mosquée à coupole bleue de la place des Martyrs, achevée en 2008, emblème du centre-ville.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Mohammad_Al-Amin_Mosque",
    },
    {
        "slug": "sursock-museum",
        "name_en": "Sursock Museum",
        "name_ar": "متحف سرسق",
        "name_fr": "Musée Sursock",
        "governorate": "beirut",
        "category": "culture",
        "listing_kind": "attraction",
        "tags": ["museum", "historic"],
        "lat": 33.8931,
        "lng": 35.5188,
        "summary_en": "A modern and contemporary art museum in a 1912 Beiruti villa in the Achrafieh district.",
        "summary_ar": "متحف للفن الحديث والمعاصر في فيلا بيروتية تعود إلى 1912 في منطقة الأشرفية.",
        "summary_fr": "Musée d'art moderne et contemporain dans une villa beyrouthine de 1912, à Achrafieh.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Sursock_Museum",
    },
    {
        "slug": "corniche-beirut",
        "name_en": "Corniche Beirut",
        "name_ar": "كورنيش بيروت",
        "name_fr": "Corniche de Beyrouth",
        "governorate": "beirut",
        "category": "city",
        "listing_kind": "attraction",
        "tags": ["promenade", "seaside", "viewpoint"],
        "lat": 33.8992,
        "lng": 35.4770,
        "summary_en": "The seafront promenade running along Beirut's western shore, lined with palm trees and popular for walking and fishing.",
        "summary_ar": "ممشى بحري يمتد على طول الواجهة الغربية لبيروت، تحفّه أشجار النخيل ويقصده الناس للمشي وصيد السمك.",
        "summary_fr": "La promenade du bord de mer longeant la côte ouest de Beyrouth, bordée de palmiers.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Corniche_Beirut",
    },
    {
        "slug": "beirut-souks",
        "name_en": "Beirut Souks",
        "name_ar": "أسواق بيروت",
        "name_fr": "Souks de Beyrouth",
        "governorate": "beirut",
        "category": "city",
        "listing_kind": "attraction",
        "tags": ["souk", "old-town"],
        "lat": 33.8975,
        "lng": 35.5060,
        "summary_en": "The rebuilt central market district downtown, on the historic site of Beirut's old souks.",
        "summary_ar": "منطقة السوق المركزية المُعاد بناؤها في وسط المدينة، على الموقع التاريخي لأسواق بيروت القديمة.",
        "summary_fr": "Le quartier commerçant central reconstruit, sur le site historique des anciens souks de Beyrouth.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Beirut_Souks",
    },
    # ===================== MOUNT LEBANON =====================
    {
        "slug": "jeita-grotto",
        "name_en": "Jeita Grotto",
        "name_ar": "مغارة جعيتا",
        "name_fr": "Grotte de Jeita",
        "governorate": "mount-lebanon",
        "category": "nature",
        "listing_kind": "attraction",
        "tags": ["cave", "landmark"],
        "lat": 33.9433889,
        "lng": 35.6413583,
        "summary_en": "A two-level system of limestone caves — an upper dry gallery and a lower river gallery visited by boat — north-east of Beirut.",
        "summary_ar": "مغاور كلسية من مستويين، رواق علوي جاف ورواق سفلي نهري يُزار بالقارب، شمال شرق بيروت.",
        "summary_fr": "Un réseau de grottes calcaires sur deux niveaux, une galerie sèche supérieure et une galerie fluviale visitée en barque.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Jeita_Grotto",
    },
    {
        "slug": "our-lady-of-lebanon-harissa",
        "name_en": "Our Lady of Lebanon, Harissa",
        "name_ar": "سيدة لبنان حريصا",
        "name_fr": "Notre-Dame du Liban, Harissa",
        "governorate": "mount-lebanon",
        "category": "culture",
        "listing_kind": "attraction",
        "tags": ["shrine", "viewpoint", "landmark"],
        "lat": 33.98167,
        "lng": 35.65139,
        "summary_en": "A Marian shrine above Jounieh bay, its white statue reached by a mountain road or a cable car, with wide views over the coast.",
        "summary_ar": "مزار مريمي يطل على خليج جونيه، يُوصل إلى تمثاله الأبيض بطريق جبلي أو بالتلفريك، مع إطلالة واسعة على الساحل.",
        "summary_fr": "Un sanctuaire marial au-dessus de la baie de Jounieh, sa statue blanche accessible par la route ou le téléphérique.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Our_Lady_of_Lebanon",
    },
    {
        "slug": "byblos-archaeological-site",
        "name_en": "Byblos (Jbeil)",
        "name_ar": "جبيل",
        "name_fr": "Byblos",
        "governorate": "mount-lebanon",
        "category": "culture",
        "listing_kind": "attraction",
        "tags": ["unesco", "archaeological-site", "phoenician", "old-town", "port"],
        "lat": 34.12361,
        "lng": 35.65194,
        "summary_en": "One of the world's oldest continuously inhabited towns and a UNESCO World Heritage site, with a Crusader castle, an old souk and a small harbour.",
        "summary_ar": "من أقدم المدن المأهولة باستمرار في العالم وموقع تراث عالمي لليونسكو، فيها قلعة صليبية وسوق قديم ومرفأ صغير.",
        "summary_fr": "L'une des plus anciennes villes habitées sans interruption et site du patrimoine mondial, avec château croisé, vieux souk et petit port.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Byblos",
    },
    {
        "slug": "byblos-castle",
        "name_en": "Byblos Castle",
        "name_ar": "قلعة جبيل",
        "name_fr": "Château de Byblos",
        "governorate": "mount-lebanon",
        "category": "culture",
        "listing_kind": "attraction",
        "tags": ["castle", "crusader", "archaeological-site"],
        "lat": 34.1214,
        "lng": 35.6455,
        "summary_en": "A 12th-century Crusader castle built from limestone and Roman-era spolia at the heart of the Byblos archaeological site.",
        "summary_ar": "قلعة صليبية من القرن الثاني عشر بُنيت من الحجر الكلسي وأنقاض رومانية في قلب موقع جبيل الأثري.",
        "summary_fr": "Un château croisé du XIIe siècle bâti en calcaire et remplois romains, au cœur du site archéologique de Byblos.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Byblos_Castle",
    },
    {
        "slug": "beiteddine-palace",
        "name_en": "Beiteddine Palace",
        "name_ar": "قصر بيت الدين",
        "name_fr": "Palais de Beiteddine",
        "governorate": "mount-lebanon",
        "category": "culture",
        "listing_kind": "attraction",
        "tags": ["palace", "ottoman", "historic"],
        "lat": 33.6944,
        "lng": 35.5806,
        "summary_en": "An early-19th-century emiri palace in the Chouf, famous for its courtyards, carved stone and Byzantine mosaic collection.",
        "summary_ar": "قصر أميري من أوائل القرن التاسع عشر في الشوف، يشتهر بباحاته وحجارته المنحوتة ومجموعة فسيفسائه البيزنطية.",
        "summary_fr": "Un palais émiral du début du XIXe siècle dans le Chouf, célèbre pour ses cours, sa pierre sculptée et ses mosaïques byzantines.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Beiteddine_Palace",
    },
    {
        "slug": "deir-el-qamar",
        "name_en": "Deir el Qamar",
        "name_ar": "دير القمر",
        "name_fr": "Deir el-Qamar",
        "governorate": "mount-lebanon",
        "category": "culture",
        "listing_kind": "attraction",
        "tags": ["village", "old-town", "historic", "ottoman"],
        "lat": 33.6961,
        "lng": 35.5586,
        "summary_en": "A well-preserved Chouf village of red-roofed stone houses that served as the seat of Mount Lebanon's emirs in the 17th–18th centuries.",
        "summary_ar": "بلدة محفوظة في الشوف من بيوت حجرية بأسقف قرميدية، كانت مقرّ أمراء جبل لبنان في القرنين السابع عشر والثامن عشر.",
        "summary_fr": "Un village du Chouf bien conservé, aux maisons de pierre à toits rouges, siège des émirs du Mont-Liban aux XVIIe–XVIIIe siècles.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Deir_el_Qamar",
    },
    {
        "slug": "mzaar-kfardebian-ski",
        "name_en": "Mzaar Kfardebian",
        "name_ar": "مزار كفردبيان",
        "name_fr": "Mzaar Kfardebian",
        "governorate": "mount-lebanon",
        "category": "adventure",
        "listing_kind": "attraction",
        "tags": ["ski", "mountain"],
        "lat": 33.9836,
        "lng": 35.8420,
        "summary_en": "Lebanon's largest ski resort, above Kfardebian, with slopes rising to around 2,465 m and summer hiking terrain.",
        "summary_ar": "أكبر منتجع تزلّج في لبنان، فوق كفردبيان، بمنحدرات ترتفع إلى نحو 2465 متراً ومسارات للمشي صيفاً.",
        "summary_fr": "La plus grande station de ski du Liban, au-dessus de Kfardebian, culminant à environ 2 465 m.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Mzaar_Kfardebian",
    },
    {
        "slug": "qalaat-faqra",
        "name_en": "Qalaat Faqra",
        "name_ar": "قلعة فقرا",
        "name_fr": "Qalaat Faqra",
        "governorate": "mount-lebanon",
        "category": "culture",
        "listing_kind": "attraction",
        "tags": ["archaeological-site", "roman", "temple", "mountain"],
        "lat": 33.9976,
        "lng": 35.8347,
        "summary_en": "The largest Roman-era site in the Lebanese mountains, with temples and a tower on a high plateau near Faqra.",
        "summary_ar": "أكبر موقع من العصر الروماني في جبال لبنان، فيه معابد وبرج على هضبة مرتفعة قرب فقرا.",
        "summary_fr": "Le plus grand site romain des montagnes libanaises, avec temples et une tour sur un haut plateau près de Faqra.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Faqra",
    },
    {
        "slug": "afqa-waterfall",
        "name_en": "Afqa",
        "name_ar": "أفقا",
        "name_fr": "Afqa",
        "governorate": "mount-lebanon",
        "category": "nature",
        "listing_kind": "attraction",
        "tags": ["waterfall", "cave", "river"],
        "lat": 34.0716,
        "lng": 35.8934,
        "summary_en": "The spring and waterfall at the source of the Adonis (Nahr Ibrahim) river, emerging from a large cave in a limestone cliff.",
        "summary_ar": "النبع والشلال عند منبع نهر إبراهيم (أدونيس)، يتدفّق من مغارة كبيرة في جرف كلسي.",
        "summary_fr": "La source et la cascade du fleuve Adonis (Nahr Ibrahim), jaillissant d'une grande grotte dans une falaise calcaire.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Afqa",
    },
    {
        "slug": "jabal-moussa-reserve",
        "name_en": "Jabal Moussa Biosphere Reserve",
        "name_ar": "محمية جبل موسى",
        "name_fr": "Réserve de biosphère du Jabal Moussa",
        "governorate": "mount-lebanon",
        "category": "nature",
        "listing_kind": "attraction",
        "tags": ["nature-reserve", "hiking", "forest", "mountain"],
        "lat": 34.0560,
        "lng": 35.7360,
        "summary_en": "A UNESCO-designated biosphere reserve between the Nahr Ibrahim and Nahr el-Dahab valleys, with marked hiking trails and old terraces.",
        "summary_ar": "محمية محيط حيوي مصنّفة لدى اليونسكو بين واديي نهر إبراهيم ونهر الذهب، فيها مسارات مشي معلّمة ومصاطب قديمة.",
        "summary_fr": "Une réserve de biosphère de l'UNESCO entre les vallées du Nahr Ibrahim et du Nahr el-Dahab, avec sentiers balisés.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Jabal_Moussa_Biosphere_Reserve",
    },
    # ===================== NORTH LEBANON =====================
    {
        "slug": "citadel-of-tripoli",
        "name_en": "Citadel of Raymond de Saint-Gilles",
        "name_ar": "قلعة طرابلس (قلعة سان جيل)",
        "name_fr": "Citadelle de Raymond de Saint-Gilles",
        "governorate": "north-lebanon",
        "category": "culture",
        "listing_kind": "attraction",
        "tags": ["citadel", "castle", "crusader", "mamluk"],
        "lat": 34.4340,
        "lng": 35.8497,
        "summary_en": "The great hilltop citadel over Tripoli, founded by the Crusaders and much rebuilt under Mamluk and Ottoman rule.",
        "summary_ar": "القلعة الكبيرة المطلّة على طرابلس، أسّسها الصليبيون وأُعيد بناؤها كثيراً في العهدين المملوكي والعثماني.",
        "summary_fr": "La grande citadelle dominant Tripoli, fondée par les croisés et largement reconstruite sous les Mamelouks et les Ottomans.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Citadel_of_Tripoli",
    },
    {
        "slug": "rachid-karami-fair-tripoli",
        "name_en": "Rachid Karami International Fair",
        "name_ar": "معرض رشيد كرامي الدولي",
        "name_fr": "Foire internationale Rachid Karamé",
        "governorate": "north-lebanon",
        "category": "culture",
        "listing_kind": "attraction",
        "tags": ["landmark", "historic", "unesco"],
        "lat": 34.4297,
        "lng": 35.8281,
        "summary_en": "An unfinished modernist exhibition complex in Tripoli designed by Oscar Niemeyer, inscribed on the UNESCO World Heritage list.",
        "summary_ar": "مجمّع معارض حداثي غير مكتمل في طرابلس صمّمه أوسكار نيماير، مُدرج على لائحة التراث العالمي لليونسكو.",
        "summary_fr": "Un ensemble d'exposition moderniste inachevé à Tripoli conçu par Oscar Niemeyer, inscrit au patrimoine mondial.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Rachid_Karami_International_Fair",
    },
    {
        "slug": "batroun-old-town",
        "name_en": "Batroun",
        "name_ar": "البترون",
        "name_fr": "Batroun",
        "governorate": "north-lebanon",
        "category": "coast",
        "listing_kind": "attraction",
        "tags": ["old-town", "seaside", "phoenician", "port"],
        "lat": 34.2553,
        "lng": 35.6581,
        "summary_en": "A small coastal town with an old quarter, churches, and a Phoenician sea wall that shelters its shore.",
        "summary_ar": "بلدة ساحلية صغيرة ذات حيّ قديم وكنائس وجدار بحري فينيقي يحمي شاطئها.",
        "summary_fr": "Une petite ville côtière au vieux quartier, aux églises et au mur phénicien qui protège son rivage.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Batroun",
    },
    {
        "slug": "msaylha-fort",
        "name_en": "Msaylha Fort",
        "name_ar": "قلعة المسيلحة",
        "name_fr": "Fort de Mseilha",
        "governorate": "north-lebanon",
        "category": "culture",
        "listing_kind": "attraction",
        "tags": ["castle", "historic"],
        "lat": 34.2661,
        "lng": 35.6717,
        "summary_en": "A 17th-century fort built on a narrow limestone rock above the Nahr el-Jaouz, near Batroun.",
        "summary_ar": "قلعة من القرن السابع عشر شُيّدت على صخرة كلسية ضيّقة فوق نهر الجوز، قرب البترون.",
        "summary_fr": "Un fort du XVIIe siècle bâti sur un rocher calcaire étroit au-dessus du Nahr el-Jaouz, près de Batroun.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Mseilha_Fort",
    },
    {
        "slug": "cedars-of-god",
        "name_en": "Cedars of God",
        "name_ar": "غابة أرز الربّ",
        "name_fr": "Forêt des Cèdres de Dieu",
        "governorate": "north-lebanon",
        "category": "nature",
        "listing_kind": "attraction",
        "tags": ["unesco", "cedars", "forest", "mountain", "hiking"],
        "lat": 34.24500,
        "lng": 36.04806,
        "summary_en": "One of the last old-growth groves of Lebanon cedar, above Bsharri, part of a UNESCO World Heritage site.",
        "summary_ar": "من آخر غابات أرز لبنان المعمّرة، فوق بشري، وجزء من موقع تراث عالمي لليونسكو.",
        "summary_fr": "L'un des derniers bosquets de cèdres du Liban anciens, au-dessus de Bcharré, inscrit au patrimoine mondial.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Cedars_of_God",
    },
    {
        "slug": "qadisha-valley",
        "name_en": "Qadisha Valley",
        "name_ar": "وادي قاديشا",
        "name_fr": "Vallée de la Qadisha",
        "governorate": "north-lebanon",
        "category": "nature",
        "listing_kind": "attraction",
        "tags": ["unesco", "hiking", "monastery", "river", "mountain"],
        "lat": 34.2506,
        "lng": 35.9500,
        "summary_en": "A deep river gorge lined with cliff monasteries and hermitages, one of the earliest Christian monastic settlements and a UNESCO site.",
        "summary_ar": "وادٍ نهري عميق تتناثر على جرفه أديرة ومحابس، من أقدم مواقع الرهبنة المسيحية وموقع تراث عالمي.",
        "summary_fr": "Une gorge profonde jalonnée de monastères et d'ermitages, l'un des plus anciens foyers monastiques chrétiens.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Kadisha_Valley",
    },
    {
        "slug": "gibran-museum-bsharri",
        "name_en": "Gibran Museum",
        "name_ar": "متحف جبران",
        "name_fr": "Musée Gibran",
        "governorate": "north-lebanon",
        "category": "culture",
        "listing_kind": "attraction",
        "tags": ["museum"],
        "lat": 34.2517,
        "lng": 36.0106,
        "summary_en": "The museum in Bsharri holding the paintings, drawings and manuscripts of writer and artist Kahlil Gibran, in a former hermitage.",
        "summary_ar": "متحف في بشري يضمّ لوحات ورسوم ومخطوطات الأديب والفنان جبران خليل جبران، في محبسة سابقة.",
        "summary_fr": "Le musée de Bcharré abritant peintures, dessins et manuscrits de l'écrivain et artiste Khalil Gibran.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Gibran_Museum",
    },
    {
        "slug": "balamand-monastery",
        "name_en": "Balamand Monastery",
        "name_ar": "دير البلمند",
        "name_fr": "Monastère de Balamand",
        "governorate": "north-lebanon",
        "category": "culture",
        "listing_kind": "attraction",
        "tags": ["monastery", "historic"],
        "lat": 34.3739,
        "lng": 35.7783,
        "summary_en": "A hilltop Greek Orthodox monastery founded on the site of a 12th-century Cistercian abbey, south of Tripoli.",
        "summary_ar": "دير للروم الأرثوذكس على تلّة، أُسّس على موقع دير سيسترسي من القرن الثاني عشر، جنوب طرابلس.",
        "summary_fr": "Un monastère grec-orthodoxe sur une colline, fondé sur le site d'une abbaye cistercienne du XIIe siècle.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Balamand",
    },
    {
        "slug": "baatara-gorge-waterfall",
        "name_en": "Baatara Gorge Waterfall",
        "name_ar": "شلال بلعة (مغارة الثلاث جسور)",
        "name_fr": "Cascade du gouffre de Baatara",
        "governorate": "north-lebanon",
        "category": "nature",
        "listing_kind": "attraction",
        "tags": ["waterfall", "cave", "hiking"],
        "lat": 34.173433,
        "lng": 35.870367,
        "summary_en": "A seasonal waterfall near Tannourine that drops through three natural stone bridges into the Baatara sinkhole.",
        "summary_ar": "شلال موسمي قرب تنورين يتساقط عبر ثلاثة جسور صخرية طبيعية إلى هوة بلعة.",
        "summary_fr": "Une cascade saisonnière près de Tannourine qui plonge à travers trois ponts de pierre naturels dans le gouffre de Baatara.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Baatara_gorge_waterfall",
    },
    {
        "slug": "tannourine-cedar-reserve",
        "name_en": "Tannourine Cedar Forest Nature Reserve",
        "name_ar": "محمية أرز تنورين",
        "name_fr": "Réserve des cèdres de Tannourine",
        "governorate": "north-lebanon",
        "category": "nature",
        "listing_kind": "attraction",
        "tags": ["nature-reserve", "cedars", "forest", "hiking", "mountain"],
        "lat": 34.2050,
        "lng": 35.9330,
        "summary_en": "One of Lebanon's densest cedar forests, a protected reserve above Tannourine with marked trails.",
        "summary_ar": "من أكثف غابات الأرز في لبنان، محمية طبيعية فوق تنورين فيها مسارات معلّمة.",
        "summary_fr": "L'une des forêts de cèdres les plus denses du Liban, une réserve protégée au-dessus de Tannourine.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Tannourine",
    },
    # ===================== AKKAR =====================
    {
        "slug": "akkar-el-atika",
        "name_en": "Akkar el-Atika",
        "name_ar": "عكار العتيقة",
        "name_fr": "Akkar el-Atika",
        "governorate": "akkar",
        "category": "culture",
        "listing_kind": "attraction",
        "tags": ["village", "castle", "historic", "viewpoint"],
        "lat": 34.5389,
        "lng": 36.1400,
        "summary_en": "A historic hill village, former seat of the Akkar emirate, with the ruins of its old citadel and wide views over the plain.",
        "summary_ar": "قرية جبلية تاريخية، مقرّ إمارة عكار سابقاً، فيها أطلال قلعتها القديمة وإطلالة واسعة على السهل.",
        "summary_fr": "Un village de montagne historique, ancien siège de l'émirat d'Akkar, avec les ruines de sa citadelle.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Akkar_District",
    },
    {
        "slug": "qammoua-forest",
        "name_en": "Qammoua Forest",
        "name_ar": "غابة القموعة",
        "name_fr": "Forêt de Qammoua",
        "governorate": "akkar",
        "category": "nature",
        "listing_kind": "attraction",
        "tags": ["forest", "hiking", "mountain", "nature-reserve"],
        "lat": 34.5560,
        "lng": 36.2830,
        "summary_en": "A high plateau of cedar, fir and juniper forest above Fnaidek in the Akkar mountains, a popular summer hiking area.",
        "summary_ar": "هضبة مرتفعة من غابات الأرز والشوح والعرعر فوق فنيدق في جبال عكار، منطقة مشي مقصودة صيفاً.",
        "summary_fr": "Un haut plateau de forêts de cèdres, sapins et genévriers au-dessus de Fnaidek, dans les montagnes d'Akkar.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Akkar_District",
    },
    # ===================== BEQAA =====================
    {
        "slug": "anjar-umayyad-city",
        "name_en": "Anjar",
        "name_ar": "عنجر",
        "name_fr": "Anjar",
        "governorate": "beqaa",
        "category": "culture",
        "listing_kind": "attraction",
        "tags": ["unesco", "archaeological-site", "umayyad", "historic"],
        "lat": 33.72583,
        "lng": 35.92972,
        "summary_en": "A rare, well-preserved Umayyad city of the early 8th century, laid out on a Roman grid, a UNESCO World Heritage site in the Beqaa.",
        "summary_ar": "مدينة أموية نادرة محفوظة من أوائل القرن الثامن، مخطّطة على شبكة رومانية، وموقع تراث عالمي في البقاع.",
        "summary_fr": "Une rare cité omeyyade bien conservée du début du VIIIe siècle, sur un plan romain, site du patrimoine mondial.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Anjar,_Lebanon",
    },
    {
        "slug": "chateau-ksara",
        "name_en": "Château Ksara",
        "name_ar": "شاتو كسارة",
        "name_fr": "Château Ksara",
        "governorate": "beqaa",
        "category": "culture",
        "listing_kind": "attraction",
        "tags": ["winery", "historic"],
        "lat": 33.8064,
        "lng": 35.8892,
        "summary_en": "Lebanon's oldest winery, near Zahlé, known for the Roman-era caves used to age its wine.",
        "summary_ar": "أقدم معمل نبيذ في لبنان، قرب زحلة، يشتهر بمغاوره الرومانية المستخدمة لتعتيق النبيذ.",
        "summary_fr": "Le plus ancien domaine viticole du Liban, près de Zahlé, connu pour ses caves d'époque romaine.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Ch%C3%A2teau_Ksara",
    },
    {
        "slug": "chateau-kefraya",
        "name_en": "Château Kefraya",
        "name_ar": "شاتو كفريا",
        "name_fr": "Château Kefraya",
        "governorate": "beqaa",
        "category": "culture",
        "listing_kind": "attraction",
        "tags": ["winery"],
        "lat": 33.6489,
        "lng": 35.7889,
        "summary_en": "A large estate winery on the western slopes of the Beqaa, with vineyards below the Barouk range.",
        "summary_ar": "معمل نبيذ كبير على السفوح الغربية للبقاع، بكرومه تحت سلسلة الباروك.",
        "summary_fr": "Un grand domaine viticole sur les pentes ouest de la Beqaa, sous la chaîne du Barouk.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Ch%C3%A2teau_Kefraya",
    },
    {
        "slug": "zahle-berdawni",
        "name_en": "Zahlé",
        "name_ar": "زحلة",
        "name_fr": "Zahlé",
        "governorate": "beqaa",
        "category": "city",
        "listing_kind": "attraction",
        "tags": ["old-town", "river", "historic"],
        "lat": 33.8463,
        "lng": 35.9019,
        "summary_en": "The main Beqaa city, set where the Berdawni river leaves the mountains, long known for its riverside restaurants and arak.",
        "summary_ar": "كبرى مدن البقاع، حيث يخرج نهر البردوني من الجبل، تشتهر منذ زمن بمطاعمها على ضفة النهر وعرقها.",
        "summary_fr": "La principale ville de la Beqaa, là où le Berdawni sort des montagnes, réputée pour ses restaurants au bord de l'eau.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Zahl%C3%A9",
    },
    {
        "slug": "taanayel-lake",
        "name_en": "Taanayel Lake",
        "name_ar": "بحيرة تعنايل",
        "name_fr": "Lac de Taanayel",
        "governorate": "beqaa",
        "category": "nature",
        "listing_kind": "attraction",
        "tags": ["lake", "nature-reserve", "garden"],
        "lat": 33.7900,
        "lng": 35.8720,
        "summary_en": "A calm lake and working farm estate in the central Beqaa, with lakeside walking paths and a historic Jesuit domain.",
        "summary_ar": "بحيرة هادئة ومزرعة عاملة في وسط البقاع، فيها ممرّات للمشي على الضفة ودير يسوعي تاريخي.",
        "summary_fr": "Un lac paisible et un domaine agricole au centre de la Beqaa, avec sentiers au bord de l'eau.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Taanayel",
    },
    {
        "slug": "lake-qaraoun",
        "name_en": "Lake Qaraoun",
        "name_ar": "بحيرة القرعون",
        "name_fr": "Lac de Qaraoun",
        "governorate": "beqaa",
        "category": "nature",
        "listing_kind": "attraction",
        "tags": ["lake", "river"],
        "lat": 33.5667,
        "lng": 35.6939,
        "summary_en": "The large reservoir on the Litani river in the south Beqaa, formed by a 1960s dam below the Barouk mountains.",
        "summary_ar": "الخزّان الكبير على نهر الليطاني في جنوب البقاع، تشكّل بسدّ من الستينيات تحت جبال الباروك.",
        "summary_fr": "Le grand réservoir sur le Litani, au sud de la Beqaa, formé par un barrage des années 1960.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Lake_Qaraoun",
    },
    # ===================== BAALBEK-HERMEL =====================
    {
        "slug": "baalbek-temples",
        "name_en": "Baalbek",
        "name_ar": "بعلبك",
        "name_fr": "Baalbek",
        "governorate": "baalbek-hermel",
        "category": "culture",
        "listing_kind": "attraction",
        "tags": ["unesco", "archaeological-site", "roman", "temple", "landmark"],
        "lat": 34.0069,
        "lng": 36.2039,
        "summary_en": "The monumental Roman sanctuary of Heliopolis, whose temples of Jupiter and Bacchus are among the largest and best-preserved in the Roman world — a UNESCO World Heritage site.",
        "summary_ar": "حرم هليوبوليس الروماني الضخم، ومعبداه لجوبيتر وباخوس من أكبر المعابد الرومانية وأفضلها حفظاً، وموقع تراث عالمي.",
        "summary_fr": "Le sanctuaire romain monumental d'Héliopolis, dont les temples de Jupiter et Bacchus comptent parmi les mieux conservés du monde romain.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Baalbek",
    },
    {
        "slug": "pyramid-of-hermel",
        "name_en": "Pyramid of Hermel",
        "name_ar": "هرم الهرمل (قاموع الهرمل)",
        "name_fr": "Pyramide de Hermel",
        "governorate": "baalbek-hermel",
        "category": "culture",
        "listing_kind": "attraction",
        "tags": ["archaeological-site", "roman", "historic", "landmark"],
        "lat": 34.3283,
        "lng": 36.3897,
        "summary_en": "A Roman-era funerary monument with a pyramidal top, standing alone on the uplands near Hermel.",
        "summary_ar": "نصب جنائزي من العصر الروماني بقمّة هرمية، يقف منفرداً على مرتفعات قرب الهرمل.",
        "summary_fr": "Un monument funéraire d'époque romaine à sommet pyramidal, isolé sur les hauteurs près de Hermel.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Hermel",
    },
    # ===================== SOUTH LEBANON =====================
    {
        "slug": "sidon-sea-castle",
        "name_en": "Sidon Sea Castle",
        "name_ar": "قلعة صيدا البحرية",
        "name_fr": "Château de la mer de Sidon",
        "governorate": "south-lebanon",
        "category": "culture",
        "listing_kind": "attraction",
        "tags": ["castle", "crusader", "seaside", "landmark"],
        "lat": 33.5670,
        "lng": 35.3711,
        "summary_en": "A 13th-century Crusader fortress built on a small island linked to Sidon's old harbour by a stone causeway.",
        "summary_ar": "قلعة صليبية من القرن الثالث عشر بُنيت على جزيرة صغيرة تصلها بمرفأ صيدا القديم جسر حجري.",
        "summary_fr": "Une forteresse croisée du XIIIe siècle bâtie sur un îlot relié au vieux port de Sidon par une chaussée.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Sidon_Sea_Castle",
    },
    {
        "slug": "temple-of-eshmun",
        "name_en": "Temple of Eshmun",
        "name_ar": "معبد إشمون",
        "name_fr": "Temple d'Echmoun",
        "governorate": "south-lebanon",
        "category": "culture",
        "listing_kind": "attraction",
        "tags": ["archaeological-site", "phoenician", "temple", "historic"],
        "lat": 33.58556,
        "lng": 35.39806,
        "summary_en": "A Phoenician sanctuary near Sidon dedicated to the healing god Eshmun, with terraces, a throne of Astarte and mosaic floors.",
        "summary_ar": "حرم فينيقي قرب صيدا مكرّس لإله الشفاء إشمون، فيه مصاطب وعرش عشتروت وأرضيات فسيفسائية.",
        "summary_fr": "Un sanctuaire phénicien près de Sidon dédié au dieu guérisseur Echmoun, avec terrasses et sols en mosaïque.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Temple_of_Eshmun",
    },
    {
        "slug": "tyre-al-bass",
        "name_en": "Tyre (Al-Bass Site)",
        "name_ar": "صور (موقع البص)",
        "name_fr": "Tyr (site d'Al-Bass)",
        "governorate": "south-lebanon",
        "category": "culture",
        "listing_kind": "attraction",
        "tags": ["unesco", "archaeological-site", "roman", "phoenician"],
        "lat": 33.2731,
        "lng": 35.2100,
        "summary_en": "The great Roman necropolis and one of the largest surviving hippodromes, part of the UNESCO World Heritage site of Tyre.",
        "summary_ar": "المدفن الروماني الكبير وأحد أكبر الحلبات الرومانية الباقية، ضمن موقع صور المدرج على التراث العالمي.",
        "summary_fr": "La grande nécropole romaine et l'un des plus vastes hippodromes conservés, au sein du site de Tyr.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Tyre,_Lebanon",
    },
    {
        "slug": "tyre-coast-reserve",
        "name_en": "Tyre Coast Nature Reserve",
        "name_ar": "محمية شاطئ صور الطبيعية",
        "name_fr": "Réserve naturelle de la côte de Tyr",
        "governorate": "south-lebanon",
        "category": "coast",
        "listing_kind": "attraction",
        "tags": ["nature-reserve", "beach", "seaside"],
        "lat": 33.2450,
        "lng": 35.1980,
        "summary_en": "A protected stretch of sandy beach, dunes and freshwater springs south of Tyre, a nesting site for sea turtles.",
        "summary_ar": "شريط محمي من الشاطئ الرملي والكثبان والينابيع العذبة جنوب صور، موقع تعشيش للسلاحف البحرية.",
        "summary_fr": "Une plage de sable protégée, avec dunes et sources, au sud de Tyr, site de ponte des tortues marines.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Tyre_Coast_Nature_Reserve",
    },
    {
        "slug": "our-lady-of-mantara-maghdouche",
        "name_en": "Our Lady of Mantara, Maghdouché",
        "name_ar": "سيدة المنطرة، مغدوشة",
        "name_fr": "Notre-Dame de Mantara, Maghdouché",
        "governorate": "south-lebanon",
        "category": "culture",
        "listing_kind": "attraction",
        "tags": ["shrine", "viewpoint", "cave"],
        "lat": 33.5486,
        "lng": 35.4183,
        "summary_en": "A hilltop Marian shrine and tower above Maghdouché, over a cave traditionally linked to the Gospel account, with views to Sidon and the sea.",
        "summary_ar": "مزار مريمي وبرج على تلّة فوق مغدوشة، فوق مغارة تُربط تقليدياً بالإنجيل، مع إطلالة على صيدا والبحر.",
        "summary_fr": "Un sanctuaire marial et une tour au-dessus de Maghdouché, sur une grotte liée à la tradition évangélique.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Maghdouch%C3%A9",
    },
    # ===================== NABATIEH =====================
    {
        "slug": "beaufort-castle",
        "name_en": "Beaufort Castle",
        "name_ar": "قلعة الشقيف (بوفور)",
        "name_fr": "Château de Beaufort",
        "governorate": "nabatieh",
        "category": "culture",
        "listing_kind": "attraction",
        "tags": ["castle", "crusader", "viewpoint", "historic"],
        "lat": 33.3244,
        "lng": 35.5320,
        "summary_en": "A Crusader hilltop castle (Qalaat al-Shqif) commanding the Litani gorge near Arnoun, with sweeping views over south Lebanon.",
        "summary_ar": "قلعة صليبية على تلّة (قلعة الشقيف) تشرف على مجرى الليطاني قرب أرنون، بإطلالة واسعة على جنوب لبنان.",
        "summary_fr": "Un château croisé (Qalaat al-Chaqif) dominant les gorges du Litani près d'Arnoun, avec de vastes panoramas.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Beaufort_Castle,_Lebanon",
    },
    {
        "slug": "hasbaya-chehab-citadel",
        "name_en": "Chehab Citadel, Hasbaya",
        "name_ar": "قلعة الشهابيين، حاصبيا",
        "name_fr": "Citadelle des Chehab, Hasbaya",
        "governorate": "nabatieh",
        "category": "culture",
        "listing_kind": "attraction",
        "tags": ["castle", "historic", "village"],
        "lat": 33.3981,
        "lng": 35.6847,
        "summary_en": "A large fortified palace in Hasbaya, held by the Chehab (Shihab) family for centuries, at the foot of Mount Hermon.",
        "summary_ar": "قصر محصّن كبير في حاصبيا، بقي بيد آل شهاب قروناً، عند سفح جبل الشيخ.",
        "summary_fr": "Un grand palais fortifié à Hasbaya, tenu par la famille Chehab pendant des siècles, au pied du mont Hermon.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Hasbaya",
    },
    {
        "slug": "marjeyoun",
        "name_en": "Marjeyoun",
        "name_ar": "مرجعيون",
        "name_fr": "Marjeyoun",
        "governorate": "nabatieh",
        "category": "city",
        "listing_kind": "attraction",
        "tags": ["village", "old-town", "viewpoint"],
        "lat": 33.3606,
        "lng": 35.5906,
        "summary_en": "A hill town of old stone houses looking over the Litani valley and Mount Hermon, historically a mixed market centre of the south.",
        "summary_ar": "بلدة جبلية من بيوت حجرية قديمة تطلّ على وادي الليطاني وجبل الشيخ، ومركز سوق مختلط تاريخياً في الجنوب.",
        "summary_fr": "Une ville de colline aux vieilles maisons de pierre dominant la vallée du Litani et le mont Hermon.",
        "image_commons": None,
        "source_url": "https://en.wikipedia.org/wiki/Marjayoun",
    },
]
