"""Private object storage and media URLs.

* Verification documents always live here, under PRIVATE_STORAGE_DIR, and are
  served only through HMAC-signed links that expire (SIGNED_URL_TTL_SECONDS).
* Listing images go to ImageKit when it is configured (app.core.imagekit);
  otherwise they are kept here too and served through long-lived signed links,
  which is enough for local development.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import json
import re
from datetime import UTC, datetime, timedelta
from pathlib import Path
from uuid import uuid4

from app.core.config import settings

_LOCAL_BACKEND = "local"
_IMAGEKIT_BACKEND = "imagekit"
# Keys are always generated by put_private_bytes: "YYYY/MM/<uuid hex>-<safe name>".
_OBJECT_KEY_PATTERN = re.compile(r"\d{4}/\d{2}/[0-9a-f]{32}-[A-Za-z0-9._-]{1,80}")


class InvalidObjectKey(ValueError):
    """Raised when an object key is not one this module could have issued."""


def storage_backend() -> str:
    """Where listing images go. Verification documents always stay local."""
    if settings.imagekit_api_key and settings.imagekit_url:
        return _IMAGEKIT_BACKEND
    return _LOCAL_BACKEND


_LOCAL_IMAGE_TTL_SECONDS = 7 * 24 * 60 * 60
_CONTENT_TYPES = {
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".png": "image/png",
    ".webp": "image/webp",
    ".pdf": "application/pdf",
}


def content_type_for(object_key: str) -> str:
    return _CONTENT_TYPES.get(Path(object_key).suffix.lower(), "application/octet-stream")


def media_url(provider: str | None, object_key: str | None) -> str | None:
    """Public URL for an approved listing image, or None when it cannot be served."""
    if not object_key:
        return None
    if object_key.startswith("https://"):
        return object_key
    if provider == _IMAGEKIT_BACKEND:
        if not settings.imagekit_url:
            return None
        from app.core.imagekit import delivery_url

        return delivery_url(object_key)
    if provider == _LOCAL_BACKEND and _OBJECT_KEY_PATTERN.fullmatch(object_key):
        return sign_object_url(object_key, ttl_seconds=_LOCAL_IMAGE_TTL_SECONDS)["url"]
    return None


def storage_root() -> Path:
    path = Path(settings.private_storage_dir)
    path.mkdir(parents=True, exist_ok=True)
    return path


def put_private_bytes(data: bytes, filename: str, content_type: str, *, public: bool = False) -> dict[str, str]:
    """Persist bytes. Verification documents must pass public=False."""
    if public:
        raise ValueError("private storage refuses public objects")
    key = f"{datetime.now(UTC).strftime('%Y/%m')}/{uuid4().hex}-{_safe_name(filename)}"
    _local_path(key).parent.mkdir(parents=True, exist_ok=True)
    _local_path(key).write_bytes(data)
    return {
        "object_key": key,
        "provider": _LOCAL_BACKEND,
        "filename": filename,
        "content_type": content_type,
        "backend": _LOCAL_BACKEND,
    }


def delete_private_bytes(object_key: str) -> None:
    """Best-effort removal, used when a stored upload could not be attached."""
    _local_path(object_key).unlink(missing_ok=True)


def read_private_bytes(object_key: str) -> bytes:
    target = _local_path(object_key)
    if not target.is_file():
        raise FileNotFoundError(object_key)
    return target.read_bytes()


def _local_path(object_key: str) -> Path:
    """Map a key to a file inside the storage root, refusing anything else."""
    if not _OBJECT_KEY_PATTERN.fullmatch(object_key):
        raise InvalidObjectKey("invalid object key")
    root = storage_root().resolve()
    target = (root / object_key).resolve()
    if root not in target.parents:
        raise InvalidObjectKey("object key escapes storage root")
    return target


def sign_object_url(object_key: str, *, ttl_seconds: int | None = None) -> dict[str, str]:
    expires = int((datetime.now(UTC) + timedelta(seconds=ttl_seconds or settings.signed_url_ttl_seconds)).timestamp())
    payload = json.dumps({"k": object_key, "e": expires}, separators=(",", ":"))
    token = base64.urlsafe_b64encode(f"{payload}.{_signature(payload)}".encode()).decode("ascii")
    return {
        "url": f"/api/v1/portal/files/{token}",
        "expires_at": datetime.fromtimestamp(expires, tz=UTC).isoformat(),
        "object_key": object_key,
        "public": "false",
    }


def verify_signed_token(token: str) -> str:
    try:
        raw = base64.urlsafe_b64decode(token.encode("ascii")).decode("utf-8")
        payload, digest = raw.rsplit(".", 1)
        if not hmac.compare_digest(_signature(payload), digest):
            raise ValueError("invalid signature")
        body = json.loads(payload)
        if int(body["e"]) < int(datetime.now(UTC).timestamp()):
            raise ValueError("expired")
        object_key = str(body["k"])
        if not _OBJECT_KEY_PATTERN.fullmatch(object_key):
            raise ValueError("invalid object key")
        return object_key
    except (ValueError, TypeError, KeyError, json.JSONDecodeError, UnicodeDecodeError) as exc:
        raise ValueError("invalid signature") from exc


def _signature(payload: str) -> str:
    return hmac.new(settings.secret_key.encode("utf-8"), payload.encode("utf-8"), hashlib.sha256).hexdigest()


def _safe_name(filename: str) -> str:
    cleaned = "".join(ch if ch.isalnum() and ch.isascii() else ch if ch in ".-_" else "-" for ch in filename)
    return cleaned[:80] or "file"
